let suggestions = [
    "Avatar 2(the wave of water)",
    "jab we met",
    "drishyam2",
    "Bholaa",
    "creed III",
    "RRR",

    "Death Note",
    "Money Heist",
    "John Wick ch 4",
    "M3GAN",
    "Pathaan",
    "Shazam Fury Of The Gods",
    "Designer",
    "Developer",
    "Web Designer",
    "Web Developer",
    "Login Form in HTML & CSS",
    "How to learn HTML & CSS",
    "How to learn JavaScript",
    "How to became Freelancer",
    "How to became Web Designer",
    "How to start Gaming Channel",
    "How to start YouTube Channel",
    "What does HTML stands for?",
    "What does CSS stands for?",
];
    